### ISSUE TITLE
add JML as administrator

### ISSUE THREAD

**Issue by nh36** [nh36/Buddhist-Transcriptional-Dialect#3]
I cannot figure out how to add JML as an administrator.

**Comment by nh36** [comment]
It is harder than you are making it out to be. The only option I am given is to add you as a collaborator. If I do, it says that you are already a collaborator. 

I wonder if the problem is that I am not an 'organization'. 

![screen shot 2017-02-17 at 5 53 15 pm](https://cloud.githubusercontent.com/assets/8865733/23076892/1f198412-f53a-11e6-8361-e6b637d08c3e.png)

**Comment by LinguList** [comment]
maybe that's really the problem! Sorry, I just saw that in
organizations, it is as I said. Can you transfer the current repo to the
digling-organization? This is where we have burmish, etc. Alternatively,
you could make a new chip-organization (or whatever you like to call it,
as "chip" is probably taken), and we'll transfer burmish, rhymes, and
this repo to this organization. But digling will be as fine, and you
have admin rights on the organization (I'll check now and otherwise add
you immediately).

**Comment by LinguList** [comment]
I just granted you all rights you need to transfer the repo to digling.
You are now also administrator on burmish and rhymes, so you can invite
new members (in case this will be needed).

**Comment by nh36** [comment]
I had already tried to transfer ownership to DigLing.

**Comment by LinguList** [comment]
no you should be able to, as I granted you the right to add repos to digling.

**Comment by nh36** [comment]
This seems to have succeeded. Please close issue if you are ready.

**Comment by LinguList** [comment]
perfect!
